PUT localhost:8003/api/v1/patients/john.doe@gmail.com/patient
Content-type: application/json; charset=utf-8

{
  "name": "John Doe",
  "email": "johndoe@gmail.com",
  "address": "123 Main St",
  "dateOfBirth": "1990-01-01",
  "isActive" : true,
  "registrationDate": "1990-01-01"
}